/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AttentionRouteImport } from './routes/attention'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LogDisputeRouteImport } from './routes/log-dispute'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ApiDisputesRouteImport } from './routes/api/disputes'
import { Route as DisputesDisputeIdRouteImport } from './routes/disputes.$disputeId'
import { Route as ApiDisputesDisputeIdRouteImport } from './routes/api/disputes.$disputeId'
import { Route as ApiVoiceConverseRouteImport } from './routes/api/voice.converse'
import { Route as ApiVoiceSpeakRouteImport } from './routes/api/voice.speak'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice.transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AttentionRoute = AttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LogDisputeRoute = LogDisputeRouteImport.update({
  id: '/log-dispute',
  path: '/log-dispute',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisputesRoute = ApiDisputesRouteImport.update({
  id: '/api/disputes',
  path: '/api/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesDisputeIdRoute = DisputesDisputeIdRouteImport.update({
  id: '/disputes/$disputeId',
  path: '/disputes/$disputeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisputesDisputeIdRoute = ApiDisputesDisputeIdRouteImport.update({
  id: '/$disputeId',
  path: '/$disputeId',
  getParentRoute: () => ApiDisputesRoute,
} as any)
const ApiVoiceConverseRoute = ApiVoiceConverseRouteImport.update({
  id: '/api/voice/converse',
  path: '/api/voice/converse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSpeakRoute = ApiVoiceSpeakRouteImport.update({
  id: '/api/voice/speak',
  path: '/api/voice/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/attention': typeof AttentionRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/log-dispute': typeof LogDisputeRoute
  '/sign-in': typeof SignInRoute
  '/api/disputes': typeof ApiDisputesRouteWithChildren
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/api/disputes/$disputeId': typeof ApiDisputesDisputeIdRoute
  '/api/voice/converse': typeof ApiVoiceConverseRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/attention': typeof AttentionRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/log-dispute': typeof LogDisputeRoute
  '/sign-in': typeof SignInRoute
  '/api/disputes': typeof ApiDisputesRouteWithChildren
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/api/disputes/$disputeId': typeof ApiDisputesDisputeIdRoute
  '/api/voice/converse': typeof ApiVoiceConverseRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/attention': typeof AttentionRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/log-dispute': typeof LogDisputeRoute
  '/sign-in': typeof SignInRoute
  '/api/disputes': typeof ApiDisputesRouteWithChildren
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/api/disputes/$disputeId': typeof ApiDisputesDisputeIdRoute
  '/api/voice/converse': typeof ApiVoiceConverseRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/attention'
    | '/dashboard'
    | '/history'
    | '/log-dispute'
    | '/sign-in'
    | '/api/disputes'
    | '/disputes/$disputeId'
    | '/api/disputes/$disputeId'
    | '/api/voice/converse'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/attention'
    | '/dashboard'
    | '/history'
    | '/log-dispute'
    | '/sign-in'
    | '/api/disputes'
    | '/disputes/$disputeId'
    | '/api/disputes/$disputeId'
    | '/api/voice/converse'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/attention'
    | '/dashboard'
    | '/history'
    | '/log-dispute'
    | '/sign-in'
    | '/api/disputes'
    | '/disputes/$disputeId'
    | '/api/disputes/$disputeId'
    | '/api/voice/converse'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AttentionRoute: typeof AttentionRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LogDisputeRoute: typeof LogDisputeRoute
  SignInRoute: typeof SignInRoute
  ApiDisputesRoute: typeof ApiDisputesRouteWithChildren
  DisputesDisputeIdRoute: typeof DisputesDisputeIdRoute
  ApiVoiceConverseRoute: typeof ApiVoiceConverseRoute
  ApiVoiceSpeakRoute: typeof ApiVoiceSpeakRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attention': {
      id: '/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof AttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-dispute': {
      id: '/log-dispute'
      path: '/log-dispute'
      fullPath: '/log-dispute'
      preLoaderRoute: typeof LogDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/disputes': {
      id: '/api/disputes'
      path: '/api/disputes'
      fullPath: '/api/disputes'
      preLoaderRoute: typeof ApiDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes/$disputeId': {
      id: '/disputes/$disputeId'
      path: '/disputes/$disputeId'
      fullPath: '/disputes/$disputeId'
      preLoaderRoute: typeof DisputesDisputeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/disputes/$disputeId': {
      id: '/api/disputes/$disputeId'
      path: '/$disputeId'
      fullPath: '/api/disputes/$disputeId'
      preLoaderRoute: typeof ApiDisputesDisputeIdRouteImport
      parentRoute: typeof ApiDisputesRoute
    }
    '/api/voice/converse': {
      id: '/api/voice/converse'
      path: '/api/voice/converse'
      fullPath: '/api/voice/converse'
      preLoaderRoute: typeof ApiVoiceConverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/speak': {
      id: '/api/voice/speak'
      path: '/api/voice/speak'
      fullPath: '/api/voice/speak'
      preLoaderRoute: typeof ApiVoiceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiDisputesRouteChildren {
  ApiDisputesDisputeIdRoute: typeof ApiDisputesDisputeIdRoute
}

const ApiDisputesRouteChildren: ApiDisputesRouteChildren = {
  ApiDisputesDisputeIdRoute: ApiDisputesDisputeIdRoute,
}

const ApiDisputesRouteWithChildren = ApiDisputesRoute._addFileChildren(
  ApiDisputesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AttentionRoute: AttentionRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LogDisputeRoute: LogDisputeRoute,
  SignInRoute: SignInRoute,
  ApiDisputesRoute: ApiDisputesRouteWithChildren,
  DisputesDisputeIdRoute: DisputesDisputeIdRoute,
  ApiVoiceConverseRoute: ApiVoiceConverseRoute,
  ApiVoiceSpeakRoute: ApiVoiceSpeakRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
